lizuk_social:
    resource: "@LizukSocialBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_stats:
    resource: "@LizukStatsBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_match:
    resource: "@LizukMatchBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_league:
    resource: "@LizukLeagueBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_main:
    resource: "@LizukMainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
