lizuk_user:
    resource: "@LizukUserBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_social:
    resource: "@LizukSocialBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_stats:
    resource: "@LizukStatsBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_match:
    resource: "@LizukMatchBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_league:
    resource: "@LizukLeagueBundle/Resources/config/routing.yml"
    prefix:   /

lizuk_main:
    resource: "@LizukMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "fos_routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
