services:
    sonata.admin.user:
        class: Lizuk\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - Lizuk\UserBundle\Entity\User
            - ~